language: ruby
cache: bundler
rvm:
  - 2.6.3
notifications:
  email:
    recipients:
      - rintze.zelle@_gmail.com
      - karcher@_u.northwestern.edu
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://retorquere-sheldon.herokuapp.com/
      - https://styles-update.zotero.org:8826/
      - https://styles-update.zotero.org:8827/
    on_success: always
    on_failure: always
    on_start: never

after_failure:
  - bundle exec sheldon
after_success:
  - bundle exec sheldon
