language: ruby
cache: bundler
rvm:
  - 2.6.3
notifications:
  email:
    recipients:
      - rintze.zelle@gmail.com
      - karcher@u.northwestern.edu
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://styles-update.zotero.org:8826/
      - https://styles-update.zotero.org:8827/
    on_success: always
    on_failure: always
    on_start: never

before_install:
  - gem update --system
  - gem install bundler
  - bundler update --bundler
before_script:
  - bundle exec sheldon --welcome
after_failure:
  - bundle exec sheldon
after_success:
  - bundle exec sheldon
