language: ruby
cache: bundler
rvm:
  - 2.4.1
notifications:
  email:
    recipients:
      - rintze.zelle@gmail.com
      - karcher@u.northwestern.edu
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://shelbot.herokuapp.com/build
      - https://styles-update.zotero.org:8826/
      - https://styles-update.zotero.org:8827/
    on_success: always
    on_failure: always
    on_start: never

after_failure:
  - ./spec/post-to-github.rb
after_success:
  - ./spec/post-to-github.rb
